language: python
python:
  - '3.6'

install:
  - pip install coverage coveralls
  - pip install pycodestyle

script:
  - pycodestyle .
  - coverage run --source=src setup.py test

after_success:
  - coveralls
